/**
 * Permisos exhaustivos del sistema agrupados por módulo.
 */
const PERMISSIONS = {
    // USUARIOS
    USERS_VIEW: 'USERS_VIEW',
    USERS_CREATE: 'USERS_CREATE',
    USERS_EDIT: 'USERS_EDIT',
    USERS_DELETE: 'USERS_DELETE',
    USERS_CHANGE_PASSWORD: 'USERS_CHANGE_PASSWORD',

    // TURNOS
    SHIFTS_VIEW: 'SHIFTS_VIEW',
    SHIFTS_CREATE: 'SHIFTS_CREATE',
    SHIFTS_EDIT: 'SHIFTS_EDIT',
    SHIFTS_DELETE: 'SHIFTS_DELETE',

    // SOLICITUDES (VACACIONES, AUSENCIAS)
    REQUESTS_VIEW: 'REQUESTS_VIEW',
    REQUESTS_CREATE: 'REQUESTS_CREATE',
    REQUESTS_APPROVE: 'REQUESTS_APPROVE',
    REQUESTS_DELETE: 'REQUESTS_DELETE',

    // INTERCAMBIOS (SWAPS)
    SWAPS_PROPOSE: 'SWAPS_PROPOSE',
    SWAPS_RESPOND: 'SWAPS_RESPOND',
    SWAPS_APPROVE: 'SWAPS_APPROVE',

    // ZONAS Y SUCURSALES
    ZONES_VIEW: 'ZONES_VIEW',
    ZONES_MANAGE: 'ZONES_MANAGE',
    BRANCHES_VIEW: 'BRANCHES_VIEW',

    // TABLÓN Y COMUNICADOS
    ANNOUNCEMENTS_VIEW: 'ANNOUNCEMENTS_VIEW',
    ANNOUNCEMENTS_CREATE: 'ANNOUNCEMENTS_CREATE',
    ANNOUNCEMENTS_EDIT: 'ANNOUNCEMENTS_EDIT',
    ANNOUNCEMENTS_DELETE: 'ANNOUNCEMENTS_DELETE',
    GLOBAL_NOTICES_MANAGE: 'GLOBAL_NOTICES_MANAGE',

    // AUDITORÍA Y BACKUPS
    AUDIT_LOGS_VIEW: 'AUDIT_LOGS_VIEW',
    BACKUPS_MANAGE: 'BACKUPS_MANAGE',

    // ROLES Y PERMISOS (ADMINISTRACIÓN)
    AUTH_ROLES_MANAGE: 'AUTH_ROLES_MANAGE',

    // ESTADÍSTICAS Y CÁLCULOS
    STATS_VIEW_OWN: 'STATS_VIEW_OWN',
    STATS_VIEW_BRANCH: 'STATS_VIEW_BRANCH',
    STATS_VIEW_GLOBAL: 'STATS_VIEW_GLOBAL',

    // AJUSTES DE VACACIONES
    VACATION_ADJUSTMENTS_MANAGE: 'VACATION_ADJUSTMENTS_MANAGE'
};

module.exports = PERMISSIONS;
